SistemaNotas/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaNotas.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Nota> Notas { get; set; }
        public DbSet<User> Users { get; set; }
    }
}

SistemaNotas/Models/ErrorViewModel.cs
using System;

namespace SistemaNotas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaNotas/Models/Nota.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaNotas.Models
{
    public class Nota
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Text { get; set; }
        public User User { get; set; }
    }
}

SistemaNotas/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaNotas.Models
{
    public class User
    {
        [Key]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

SistemaNotas/Controllers/HomeController.cs
using SistemaNotas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace SistemaNotas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            // return login view if user is not logged in
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Login", "Users");
            }
            ViewBag.Username = HttpContext.Session.GetString("Username");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaNotas/Controllers/NotasController.cs
using SistemaNotas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace SistemaNotas.Controllers
{
    public class NotasController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public Nota Nota { get; set; }
        public NotasController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            // return login view if user is not logged in
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Login", "Users");
            }
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            // return login view if user is not logged in
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Login", "Users");
            }
            Nota = new Nota();
            if (id == null)
            {
                // create
                return View(Nota);
            }
            // update
            Nota = _db.Notas.FirstOrDefault(u => u.Id == id);
            if (Nota == null)
            {
                return NotFound();
            }
            return View(Nota);
        }

        public IActionResult View(int? id)
        {
            // return login view if user is not logged in
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Login", "Users");
            }
            Nota = _db.Notas.FirstOrDefault(u => u.Id == id);
            if (Nota == null)
            {
                return NotFound();
            }
            return View(Nota);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            // return login view if user is not logged in
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Login", "Users");
            }
            if (ModelState.IsValid)
            {
                if (Nota.Id == 0)
                {
                    // create
                    Nota.User = _db.Users.FirstOrDefault(u => u.Username == HttpContext.Session.GetString("Username"));
                    _db.Notas.Add(Nota);
                }
                else
                {
                    _db.Notas.Update(Nota);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Nota);
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            // return user notes
            var user = _db.Users.FirstOrDefault(u => u.Username == HttpContext.Session.GetString("Username"));
            return Json(new { data = await _db.Notas.Where(u => u.User.Username == user.Username).ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var notaFromDb = await _db.Notas.FirstOrDefaultAsync(u => u.Id == id);
            if (notaFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Notas.Remove(notaFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion
    }
}

SistemaNotas/Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaNotas.Models;
using System;
using System.Linq;
using System.Security.Cryptography;

namespace SistemaNotas.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public new User User { get; set; }
        public UsersController(ApplicationDbContext db)
        {
            _db = db;
        }

        private static string Hash(byte[] input, string algorithm = "sha256")
        {
            using (var hashAlgorithm = HashAlgorithm.Create(algorithm))
            {
                return Convert.ToBase64String(hashAlgorithm.ComputeHash(input));
            }
        }

        public IActionResult Register()
        {
            ViewBag.Title = "Registrarse";
            return View("Auth");
        }
        public IActionResult Login()
        {
            ViewBag.Title = "Ingresar";
            return View("Auth");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                // hash password
                user.Password = Hash(System.Text.Encoding.UTF8.GetBytes(user.Password));
                _db.Users.Add(user);
                try
                {
                    _db.SaveChanges();
                }
                catch (System.Exception)
                {
                    return RedirectToAction("Register");
                }
            }
            return RedirectToAction("Login");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User user)
        {
            if (ModelState.IsValid)
            {
                var userExists = _db.Users.Where(u => u.Username == user.Username).FirstOrDefault();
                if (userExists != null)
                {
                    // check if hashed password matches
                    if (userExists.Password == Hash(System.Text.Encoding.UTF8.GetBytes(user.Password)))
                    {
                        // create session
                        HttpContext.Session.SetString("Username", user.Username);
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return RedirectToAction("Login");
        }
    }
}

SistemaNotas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var username = ViewBag.Username;
}

<div class="text-center">
    <h1 class="display-4">Welcome @username</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaNotas/Views/Notas/Index.cshtml
<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Nota List</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Notas" class="btn btn-info form-control text-white">
            Add New Nota
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Text</th>
                    <th></th>
                </tr>
            </thead>
        </table> 
    </div>
</div>

@section Scripts{
    <script src="~/js/notaList.js">

    </script>    
}

SistemaNotas/Views/Notas/Upsert.cshtml
@model SistemaNotas.Models.Nota

<br />
<h2 class="text-info">@(Model.Id!=0 ? "Edit" : "Create") Nota</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-dangers" asp-validation-summary="ModelOnly">

        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Name">
                </label>
            </div>
            <div class="col-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger">

                </span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Text">
                </label>
            </div>
            <div class="col-6">
                <textarea asp-for="Text" class="form-control">
                </textarea>
                <span asp-validation-for="Text" class="text-danger">

                </span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id!=0 ? "Update" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{ 
<partial name="_ValidationScriptsPartial" />
}

SistemaNotas/Views/Notas/View.cshtml
@model SistemaNotas.Models.Nota

<br />
<h2 class="text-info">Ver Nota</h2>
<br />

<div class="border container" style="padding:30px;">
    <markdown>@Model.Text</markdown>
</div>

SistemaNotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaNotas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaNotas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notas" asp-action="Index">Notes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SistemaNotas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SistemaNotas/Views/Users/Auth.cshtml
@model SistemaNotas.Models.User
@{   
    var title = ViewBag.Title;  
}  
<br />
<h2 class="text-info">@title</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Username">
                </label>
            </div>
            <div class="col-6">
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger">

                </span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Password">
                </label>
            </div>
            <div class="col-6">
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger">

                </span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @title
                </button>
            </div>
        </div>
    </form>
</div>